services:
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama-container
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   restart: always

  app:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-app
    environment:
      - STREAMLIT_WATCHER_TYPE=none
      - LLAMA_HOST=http://host.docker.internal:11434  # 👈 Tell app where to find Ollama
    ports:
      - "8501:8501"
    # command: ["bash", "-c", "pull gemma:2b"]
    volumes:
      - faiss_data:/app/src/faiss_index
    # depends_on:
    #   - ollama
    env_file:
      - ./src/.env
    # networks:
    #   - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 👈 Important! Map host.docker.internal correctly

volumes:
  # ollama_data:
  faiss_data:

networks:
  app-network:
    driver: bridge
